server:
  port: 5000
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://awseb-e-ckvc3c9mq3-stack-awsebrdsdatabase-ou5wycndzqjp.cc9cyokkk9iw.us-east-1.rds.amazonaws.com:3306/ebdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: testpm
    password: "gogotkddnr7."